In [8]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
df = pd.read_csv('ndf.csv')
X = df.drop('price', axis=1)  # Adjust the column name for your target variable
y = df['price']

# Standardize the features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Apply PCA
pca = PCA(n_components=2)  # Set the number of components you want to retain
X_pca = pca.fit_transform(X_scaled)

# Create a new DataFrame with the reduced dimensions
df_pca = pd.DataFrame(data=X_pca, columns=['PC1', 'PC2'])

# Concatenate the reduced dimensions with the target variable
df_pca_target = pd.concat([df_pca, y], axis=1)

# Save the PCA-reduced dataset to a new CSV file
df_pca_target.to_csv('pca_reduced.csv', index=False)

In [9]:
df_pca_target

          PC1       PC2  price
0   -1.729328 -0.725916    900
1    5.348056 -0.641032   4125
2    2.726623 -2.103302   1259
3    3.875225  1.935037    920
4    5.843353  0.442368   2000
..        ...       ...    ...
730 -2.658943 -2.307302    489
731 -0.175826  2.481326    929
732 -3.574309  0.856212    970
733 -3.087850 -2.687617    487
734 -3.225920  0.884599    437

[735 rows x 3 columns]

In [10]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score

# Load the PCA-reduced dataset
df_pca_target = pd.read_csv('pca_reduced.csv')

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(df_pca_target[['PC1', 'PC2']], df_pca_target['price'], test_size=0.2, random_state=42)

# Train a linear regression model
model = LinearRegression()
model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test)

# Evaluate the model using mean squared error
mse = mean_squared_error(y_test, y_pred)
print('Mean Squared Error:', mse)
r2 = r2_score(y_test, y_pred)

# Display the R2 score
print('R2 score:', r2)

Mean Squared Error: 2547095.8379387306
R2 score: 0.15582564129315157

In [4]:
from pycaret.regression import *
import pandas as pd
data = pd.read_csv('ndf.csv')

regression_setup = setup(
    data,
    target='price',
    normalize=True,
    train_size=0.8,
    session_id=123,
    log_experiment=True,
    experiment_name='your_experiment_name'
)

best_models = compare_models()

print(best_models)

Processing:   0%|          | 0/77 [00:00<?, ?it/s]

GradientBoostingRegressor(random_state=123)